version: '3.8'

services:

  db:

    image: postgres:15

    container_name: 'quiz_db'

    env_file:
      - .env 

    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    
    volumes:
      - .postgres:/var/lib/postgres/data

    restart: always



  app:
    container_name: 'quiz_app'

    build:
      context: .

    depends_on:
      - db

    env_file:
      - .env

    command: bash -c "alembic upgrade head; gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

    ports:
      - 9999:8000

    


  