"""update answer_body column

Revision ID: 7428811e7e1a
Revises: 7f4ff17edae0
Create Date: 2024-04-22 10:00:53.495846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7428811e7e1a'
down_revision: Union[str, None] = '7f4ff17edae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_body', sa.String(), nullable=True))
    op.drop_column('questions', 'response_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('response_body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('questions', 'answer_body')
    # ### end Alembic commands ###
